### ISSUE TITLE
Notion 백엔드 기능 명세 작성

### ISSUE THREAD

**Issue by GrassHopper42** [42delicious/backend#1]
현재 노션 API로 이루어지는 데이터 조회 기능 명세
쿼리스트링, 파라미터, 바디와 반환값, 조회했을 때 발생하는 이벤트 포함.

**Comment by Junsang-Mun** [comment]
그런데 이거 ... 꼭 현재 명세 그대로 옮겨야 할까요? 현재 명세는 워낙 개판이라 문서화가 두려운데 ㄷㄷ
차라리 차후 계획을 명세로 옮겨보는 것도 나쁘지 않을 것 같단 생각이에요

**Comment by GrassHopper42** [comment]
그럼 제가 초안 써볼까요? 준문님 레포 참고하면 되죠?

**Comment by Junsang-Mun** [comment]
네, 기본적으로 제 레퍼지토리 참고하셔도 괜찮습니다.
다만 밑바닥부터 다시 만드는게 어떨까 싶은 생각이 있어요.
@weejihye @kangmin5505 어떻게 생각하세요?

**Comment by kangmin5505** [comment]
@Junsang-Mun 저는 이번주에 제가 주도적으로 무언가를 할 수 없는 상황이라 따르도록 하겠습니다!

**Comment by GrassHopper42** [comment]
그럼 내일 회의에서 필요 기능 정하는걸로 할까요?

**Comment by Junsang-Mun** [comment]
네 그럼 내일 회의때 한번 얘기해보시죠! Kangkim님은 내일 참석 못 하실테니 제외해야겠지만... 🥲

**Comment by Junsang-Mun** [comment]
회의록:
https://github.com/42delicious/meetings/blob/main/%5Bdoc%5D%20230418%20%EA%B8%B0%EB%8A%A5%EB%AA%85%EC%84%B8

API Endpoint 두 개 (단건 조회, 리스트 조회) 만들고 Restful한 API 만들기로 결정했습니다.
(api url)/store/:id
(api url)/store/list?cluster=서초(개포)

이슈 닫습니다!
