### ISSUE TITLE
[API] 단건 조회 Endpoint 생성

### ISSUE THREAD

**Issue by Junsang-Mun** [42delicious/backend#3]
역시 @GrassHopper42 님이 TDD용 Test Code 짜 주시기로

단건 조회
        1. 들고 있는거 다 주면 됨.
        2. rdb이고 새로운 컬럼이 생겼기 때문에 pk 기준으로 id가 들어감

**Comment by Junsang-Mun** [comment]
5/24 Test
- 단건 조회: All pass
- 전체 조회:
  - lat, lng 함께 조회되는 이슈
  - cluster 조회 불가능한 이슈

**Comment by Junsang-Mun** [comment]
@GrassHopper42 화유님, 혹시 저희 전체 조회건에서 왜 위경도값을 제외해야 하는지 이야기했던 부분이 있었나요?

**Comment by GrassHopper42** [comment]
제외해야할 이유가 있어 제외했다기보다는 전체조회할 때 사용되는 데이터가 아니라 안넣었던 것 같은데요

**Comment by Junsang-Mun** [comment]
들어가도 크게 상관은 없겠죠? 오버헤드가 감당 못할 수준으로 걸리진 않을 것 같아요

**Comment by GrassHopper42** [comment]
네 문제가 되는 사항은 아닙니다

**Comment by Junsang-Mun** [comment]
Commit 08d2a67 으로 이슈 닫습니다.
